# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-07 21:12
from __future__ import unicode_literals

import ckeditor.fields
import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('fontr', models.CharField(max_length=200)),
                ('imagem', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=b'')),
                ('texto', ckeditor.fields.RichTextField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da cria\xe7\xe3o')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da publica\xe7\xe3o')),
            ],
            options={
                'ordering': ('-data_publicacao',),
            },
        ),
    ]
