# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreraspberry', '0003_desenvolvedor2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Desenvolvedor',
        ),
    ]
