# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 00:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreraspberry', '0004_delete_desenvolvedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atareuniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor.fields.RichTextField(verbose_name='Descri\xe7\xe3o da Ata')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da cria\xe7\xe3o')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da publica\xe7\xe3o')),
            ],
            options={
                'ordering': ('-data_publicacao',),
            },
        ),
    ]
