# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 04:59
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreraspberry', '0005_atareuniao'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria'), upload_to=b'', verbose_name='Imagem')),
                ('descricao', models.CharField(blank=True, default='', max_length=200, verbose_name='Descri\xe7\xe3o')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da cria\xe7\xe3o')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da publica\xe7\xe3o')),
            ],
            options={
                'verbose_name': 'Imagens do produto',
            },
        ),
    ]
