# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreraspberry', '0006_galeriaimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeriaimage',
            options={'verbose_name': 'Imagens da Galeria'},
        ),
    ]
