# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 23:22
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreraspberry', '0007_auto_20171014_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaFotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen1', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria'), upload_to=b'', verbose_name='Imagem - 1')),
                ('imagen2', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria'), upload_to=b'', verbose_name='Imagem - 2')),
                ('imagen3', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria'), upload_to=b'', verbose_name='Imagem - 3')),
                ('imagen4', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria'), upload_to=b'', verbose_name='Imagem - 4')),
                ('imagen5', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria'), upload_to=b'', verbose_name='Imagem - 5')),
                ('texto', models.CharField(max_length=300, verbose_name='Descri\xe7\xe3o')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da cria\xe7\xe3o')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da publica\xe7\xe3o')),
            ],
            options={
                'verbose_name': 'Imagens da Galeria',
            },
        ),
        migrations.DeleteModel(
            name='GaleriaImage',
        ),
        migrations.AlterModelOptions(
            name='atareuniao',
            options={'ordering': ('-data_publicacao',), 'verbose_name': 'Ata de Reuni\xf5e'},
        ),
        migrations.AlterModelOptions(
            name='desenvolvedor2',
            options={'ordering': ('-data_publicacao',), 'verbose_name': 'Desenvolvedore'},
        ),
    ]
