# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 01:01
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreraspberry', '0008_auto_20171014_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem')),
                ('texto', models.CharField(max_length=300, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da criação')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da publicação')),
            ],
            options={
                'verbose_name': 'Foto Galeria',
                'ordering': ('-data_publicacao',),
                'verbose_name_plural': 'Fotos da Galeria',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('fotos', models.ManyToManyField(to='coreraspberry.Foto')),
            ],
            options={
                'verbose_name': 'Galeria Foto',
                'ordering': ('nome',),
                'verbose_name_plural': 'Galeria de Foto',
            },
        ),
        migrations.AlterModelOptions(
            name='galeriafotos',
            options={'verbose_name': 'Fotos da Galeria'},
        ),
        migrations.AlterField(
            model_name='desenvolvedor2',
            name='imagem',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='galeriafotos',
            name='imagen1',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem - 1'),
        ),
        migrations.AlterField(
            model_name='galeriafotos',
            name='imagen2',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem - 2'),
        ),
        migrations.AlterField(
            model_name='galeriafotos',
            name='imagen3',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem - 3'),
        ),
        migrations.AlterField(
            model_name='galeriafotos',
            name='imagen4',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem - 4'),
        ),
        migrations.AlterField(
            model_name='galeriafotos',
            name='imagen5',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/galeria/'), upload_to='', verbose_name='Imagem - 5'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='imagem',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=''),
        ),
    ]
