# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreraspberry', '0010_auto_20171016_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='texto',
        ),
        migrations.AddField(
            model_name='galeria',
            name='texto',
            field=models.CharField(default=1, max_length=300, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
