# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreraspberry', '0011_auto_20171016_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ('-data_publicacao',), 'verbose_name': 'Galeria Foto', 'verbose_name_plural': 'Galeria de Foto'},
        ),
        migrations.AlterModelOptions(
            name='galeriafotos',
            options={'verbose_name': 'Galeria'},
        ),
        migrations.RemoveField(
            model_name='foto',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='foto',
            name='galeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_da_galeria_model', to='coreraspberry.Galeria'),
        ),
    ]
