# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreraspberry', '0012_auto_20171017_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='titulo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
