# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-21 16:24
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreraspberry', '0013_foto_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Titulo da Foto'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome da Galeria'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='texto',
            field=models.CharField(max_length=300, verbose_name='Descrição da Galeria'),
        ),
        migrations.AlterField(
            model_name='galeriafotos',
            name='imagen1',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='', verbose_name='Imagem - 1'),
        ),
        migrations.AlterField(
            model_name='galeriafotos',
            name='imagen2',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='', verbose_name='Imagem - 2'),
        ),
        migrations.AlterField(
            model_name='galeriafotos',
            name='imagen3',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='', verbose_name='Imagem - 3'),
        ),
        migrations.AlterField(
            model_name='galeriafotos',
            name='imagen4',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='', verbose_name='Imagem - 4'),
        ),
        migrations.AlterField(
            model_name='galeriafotos',
            name='imagen5',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='', verbose_name='Imagem - 5'),
        ),
    ]
